# Generated by Django 4.1.4 on 2023-01-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
