# Generated by Django 4.1.4 on 2022-12-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApi', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
